config/routes.rb
Rails.application.routes.draw do
  
  resources :countries
  # bug user create via devise route/registration
  post 'users' => 'users#create'
  
  devise_for :users
  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'articles/inactive' => 'articles#index_inactive'
  
  # scaffold defaults
  resources :comments
  resources :articles
  resources :users
  
end

app/models/comment.rb
class Comment < Segment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
    set_article
  end

  # GET /comments/new
  def new
    @comment = Comment.new
    set_article
  end

  # GET /comments/1/edit
  def edit
    set_article
  end

  # POST /comments
  # POST /comments.json
  def create
    @article = Article.find_by_id(params[:article_id])
    @comment = Comment.new(comment_params)

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    set_article
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to({ controller: 'articles', action: 'show', notice: 'Comment was successfully deleted.'}.merge(id: @article.id))  }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    def set_article
      article_id = @comment.parent_id.present? ? @comment.parent_id : params[:article_id]
      @article = Article.find_by_id(article_id)
    end
  
    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      prepare_params
    end

    def prepare_params
      params[:comment][:parent_type]  ||= "Article"
      params[:comment][:parent_id]    ||= params[:article_id]
      params[:comment][:user_id]      ||= current_user.id
      params.require(:comment).permit(:type, :title, :content, :active, :parent_type, :parent_id, :user_id)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<%= form_for(comment) do |f| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :style => 'width: 400px;' %>
  </div>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_area :content, size: "140x10" %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div>
    <%= hidden_field_tag :article_id, @article.id %>
  </div>

  <div style="padding-top: 10px; ">
    <div class="drow">
      <div class="dcell"><%= f.submit %></div>
      <div class="dcell"><%= link_to '<button type="button">Cancel</button>'.html_safe, article_path(id: @article.id) %></div>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<div style="margin-top: 20px;">
  <div class="field">
    <h3><%= @article.title %></h3>
  </div>

  <div class="field">
    <%= text_area_tag :content, @article.content, size: "140x13", :disabled => true, :style => "overflow-y: scroll; resize: none; padding: 10px;" %>
  </div>
</div>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Type</th>
      <th>Title</th>
      <th>Content</th>
      <th>Active</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.type %></td>
        <td><%= comment.title %></td>
        <td><%= comment.content %></td>
        <td><%= comment.active %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment, :article_id => comment.parent_id) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h2><%= "Write a Comment for article: '#{@article.title}'" %></h2>

<%= render 'form', comment: @comment %>

<div style="margin-top: 20px;">
  <div class="field">
    <h3><%= @article.title %></h3>
  </div>

  <div class="field">
    <%= text_area_tag :content, @article.content, size: "140x13", :disabled => true, :style => "overflow-y: scroll; resize: none; padding: 10px;" %>
  </div>
</div>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<div style="padding-bottom: 10px;">
  <div class="drow">
    <div class="dcell"><%= link_to '<button type="button">Edit comment</button>'.html_safe, edit_comment_path(@comment) %></div>
    <div class="dcell"><%= link_to '<button type="button">Return to article</button>'.html_safe,
                                   article_path(id: @comment.parent_id)  if is_owner?(@comment.user) %>
    </div>
    <div class="dcell"><%= link_to '<button type="button">Delete comment</button>'.html_safe,
       @comment, method: :delete, data: { confirm: 'Are you sure?' }  if is_owner?(@comment.user) || has_admin_right? %>
    </div>
  </div>
</div>

<div style="border: solid 1px lightgray; padding: 0 10px 5px 10px; width: 600px; margin-bottom: 20px; font-size: 9pt;">
  <div>
    <div class="drow">
      <div class="dcell">
        <h3><%= @comment.title %></h3>
      </div>
    </div>
  </div>

  <div>
    <div class="drow" style="font-style: italic;">
      <div class="dcell">
        <b>Author: </b><%= "#{@comment.user.name}" %>
      </div>
      <div class="dcell">
        <b>Created: </b><%= "#{ts(@comment.created_at)}" %>
      </div>
      <div class="dcell">
        <% if @comment.created_at != @comment.updated_at %>
            <b>Modified: </b><%= "#{ts(@comment.updated_at)}" %>
        <% end %>
      </div>
    </div>
  </div>

  <div style="padding-top: 10px;">
    <%= @comment.content %>
  </div>

</div>

<div style="border: solid 1px lightskyblue; padding: 15px; width: 700px; margin-bottom: 20px;">
  <div>
    <div class="drow">
      <div class="dcell">
        <h3><%= @article.title %></h3>
      </div>
    </div>
  </div>

  <div>
    <div class="drow" style="font-style: italic;">
      <div class="dcell">
        <b>Author: </b><%= "#{@article.user.name}" %>
      </div>
      <div class="dcell">
        <b>Created: </b><%= "#{ts(@article.created_at)}" %>
      </div>
      <div class="dcell">
        <% if @article.created_at != @article.updated_at %>
            <b>Modified: </b><%= "#{ts(@article.updated_at)}" %>
        <% end %>
      </div>
    </div>
  </div>

  <div style="padding-top: 10px;">
    <%= @article.content %>
  </div>
</div>