config/routes.rb
Rails.application.routes.draw do
  
  resources :countries
  # bug user create via devise route/registration
  post 'users' => 'users#create'
  
  devise_for :users
  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'articles/inactive' => 'articles#index_inactive'
  
  # scaffold defaults
  resources :comments
  resources :articles
  resources :users
  
end

app/models/article.rb
class Article < Segment
  
  scope :active_segments, -> do
    includes(:comments)
    .where(active: true)
  end

  scope :inactive_segments, -> do
    includes(:comments)
      .where(active: false)
  end
  
  def number_of_comments
    self.comments.active_segments.size
  end
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:index_inactive]
  
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.active_segments
  end

  # GET /articles/inactive
  def index_inactive
    
    @articles = Article.inactive_segments
    respond_to do |format|
        format.html { render :index_inactive }
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      prepare_params
    end

    def prepare_params
      params[:article][:parent_type]  ||= "User"
      params[:article][:parent_id]    ||= current_user.id
      params[:article][:user_id]      ||= current_user.id
      params.require(:article).permit(:title, :content, :active, :parent_type, :parent_id, :user_id)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, :style => 'width: 400px;' %>
  </div>

  <div class="field">
    <%= f.label 'Text' %>
    <%= f.text_area :content, size: "140x25" %>
  </div>

  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>

  <div style="padding-top: 10px; ">
    <div class="drow">
      <div class="dcell"><%= f.submit %></div>
      <div class="dcell"><%= link_to '<button type="button">Cancel</button>'.html_safe, articles_path %></div>
    </div>
  </div>

<% end %>

app/views/articles/_index_content.html.erb
<div>
  <% @articles.each_with_index do |article, idx| %>
      <div style="border: solid 1px lightskyblue; padding: 15px; width: 700px; margin-bottom: 20px;">
        <div>
          <div class="drow">
            <div class="dcell">
              <%= "Article ##{idx+1}" %>
            </div>
            <div class="dcell">
              <h3><%= article.title %></h3>
            </div>
          </div>
        </div>

        <div>
          <div class="drow" style="font-style: italic;">
            <div class="dcell">
              <b>Author: </b><%= "#{article.user.name}" %>
            </div>
            <div class="dcell">
              <b>Created: </b><%= "#{ts(article.created_at)}" %>
            </div>
            <div class="dcell">
              <% if article.created_at != article.updated_at %>
                  <b>Modified: </b><%= "#{ts(article.updated_at)}" %>
              <% end %>
            </div>
          </div>
        </div>

        <div style="padding-top: 10px;">
          <%= article.preview %>
          <i><%= link_to 'Show complete article', article %></i>
        </div>

        <div style="padding-top: 10px; ">
          <div class="drow">
            <div class="dcell" style="padding-right: 60px;">
              <b>Comments: </b>
              <% if article.comments.active_segments.present? %>
                  <%= link_to("#{article.number_of_comments}", article_path(article, anchor: "comments")) %>
              <% else %>
                  0
              <% end %>
            </div>
            <div class="dcell" style="padding-right: 20px; width: 130px;">

              <%# !!! I decided that an author can comment his article, removed: && !is_owner?(article.user) %>
              <%= link_to 'Comment Article',
                new_comment_path(:article_id => article.id)  if has_user_right? %>
            </div>
            <div class="dcell"><%= link_to 'Edit article',
                                           edit_article_path(article)  if is_owner?(article.user) %>
            </div>
            <div class="dcell"><%= link_to 'Delete article', article, method: :delete,
                                           data: { confirm: 'Are you sure?' }  if is_owner?(article.user) || has_admin_right? %>
            </div>
          </div>
        </div>

      </div>
  <% end %>
</div>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

app/views/articles/index.html.erb
<div>
  <p id="notice"><%= notice %></p>
</div>

<div class="drow">
  <div class="dcell">
    <h1>Articles </h1>
  </div>
  <div class="dcell" style="padding-right: 20px;">
    <%= @articles.size > 0 ? "(#{@articles.size} total)" : "(no articles exist yet)" %>
  </div>
  <div class="dcell">
    <%= link_to 'Write new article', new_article_path  if has_user_right? %>
  </div>
</div>

<%= render 'index_content' %>

app/views/articles/index_inactive.html.erb
<div>
  <p id="notice"><%= notice %></p>
</div>

<div class="drow">
  <div class="dcell">
    <h1>Inactive Articles </h1>
  </div>
  <div class="dcell" style="padding-right: 20px;">
    <%= @articles.size > 0 ? "(#{@articles.size} total)" : "(no articles exist yet)" %>
  </div>
</div>

<%= render 'index_content' %>

app/views/articles/new.html.erb
<h1>Write new Article</h1>

<%= render 'form', article: @article %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<div style="padding-bottom: 10px;">
  <div class="drow">
    <div class="dcell"><%= link_to '<button type="button">Return to Articles</button>'.html_safe, articles_path %></div>
    <div class="dcell"><%= link_to '<button type="button">Edit Article</button>'.html_safe,
                                   edit_article_path(@article)  if is_owner?(@article.user) %>
    </div>
    <div class="dcell"><%= link_to '<button type="button">Delete Article</button>'.html_safe,
        @article, method: :delete, data: { confirm: 'Are you sure?' }  if is_owner?(@article.user) || has_admin_right? %>
    </div>
    <div class="dcell" style="padding-right: 20px; width: 130px;">
      <%# !!! I decided that an author can comment his article, removed: && !is_owner?(article.user) %>
      <%= link_to '<button type="button">Comment Article</button>'.html_safe,
                  new_comment_path(:article_id => @article.id)  if has_user_right? %>
    </div>
  </div>
</div>

<div style="border: solid 1px lightskyblue; padding: 15px; width: 700px; margin-bottom: 20px;">
  <div>
    <div class="drow">
      <div class="dcell">
        <h3><%= @article.title %></h3>
      </div>
    </div>
  </div>

  <div>
    <div class="drow" style="font-style: italic;">
      <div class="dcell">
        <b>Author: </b><%= "#{@article.user.name}" %>
      </div>
      <div class="dcell">
        <b>Created: </b><%= "#{ts(@article.created_at)}" %>
      </div>
      <div class="dcell">
        <% if @article.created_at != @article.updated_at %>
            <b>Modified: </b><%= "#{ts(@article.updated_at)}" %>
        <% end %>
      </div>
    </div>
  </div>

  <div style="padding-top: 10px;">
    <%= @article.content %>
  </div>
</div>

<div style="margin-top: 10px; margin-left: 20px;">
  <div>
      <a href="#comments"></a>
      <h4><%= @article.comments.active_segments.present? ? "Comments for this article: #{@article.comments.active_segments.size}" : "No Comments yet." %></h4>
  </div>
  <% if @article.comments.active_segments.present? %>
    <% @article.comments.active_segments.each_with_index do |comment, index_comment| %>

      <div style="border: solid 1px lightgray; padding: 0 10px 5px 10px; width: 600px; margin-bottom: 20px; font-size: 9pt;">
        <div>
          <div class="drow">
            <div class="dcell">
              <h3><%= comment.title %></h3>
            </div>
          </div>
        </div>

        <div>
          <div class="drow" style="font-style: italic;">
            <div class="dcell">
              <b>Author: </b><%= "#{comment.user.name}" %>
            </div>
            <div class="dcell">
              <b>Created: </b><%= "#{ts(comment.created_at)}" %>
            </div>
            <div class="dcell">
              <% if comment.created_at != comment.updated_at %>
                  <b>Modified: </b><%= "#{ts(comment.updated_at)}" %>
              <% end %>
            </div>
          </div>
        </div>

        <div style="padding-top: 10px;">
          <%= comment.content %>
        </div>

        <div style="padding: 5px 0;">
          <div class="drow">
            <div class="dcell"><%= link_to '<button type="button">Edit Comment</button>'.html_safe,
                                           edit_comment_path(comment)  if is_owner?(comment.user) %>
            </div>
            <div class="dcell"><%= link_to '<button type="button">Delete Comment</button>'.html_safe,
                  comment, method: :delete,
                  data: { confirm: 'Are you sure?' }  if is_owner?(comment.user) || has_admin_right? %>
            </div>
          </div>
        </div>

      </div>
    <% end %>
  <% end %>
</div>