config/routes.rb
Rails.application.routes.draw do
  
  resources :countries
  # bug user create via devise route/registration
  post 'users' => 'users#create'
  
  devise_for :users
  root 'articles#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'articles/inactive' => 'articles#index_inactive'
  
  # scaffold defaults
  resources :comments
  resources :articles
  resources :users
  
end

app/views/layouts/_footer.html.erb
<div style="display: inline-block;">
  <div class="drow">
    <div class="dcell" style="padding-right: 20px;">
      Simple Comment Version <b><%= " #{ApplicationController::VERSION_SC}" %></b>
    </div>
    <div class="dcell" style="padding-right: 20px;">
      &copy;<%= "Joerg Kirschstein" %>
    </div>
    <div class="dcell">
      <%= link_to 'sc @ Github', 'http://www.github.com/frontimax', :target => '_blank' %>
    </div>
  </div>
</div>

app/views/layouts/_menue.html.erb
<div>
  <h2>Simple Comment Demo App</h2>
</div>

<div class="drow">
  <div class="dcell">
    <%= link_to 'Show Articles', articles_path %>
  </div>
  <div class="dcell">
    <%= link_to 'Show Users [Admin only]', users_path  if has_admin_right? %>
  </div>
  <div class="dcell">
    <%= link_to 'Show Inactive Articles [Admin only]', articles_inactive_path   if has_admin_right? %>
  </div>
  <div class="dcell">
    <%#= link_to 'Show Comments', comments_path  if has_admin_right? %>
  </div>

  <% if user_signed_in? %>
    <div class="dcell" style="padding-left: 30px;">
      <%= link_to "Log out [#{current_user.name}]", destroy_user_session_path, :method => :delete %>
    </div>
  <% else %>
      <div class="dcell" style="padding-left: 30px;">
      <%= link_to 'Log in', new_user_session_path %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sc</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="sc_body" style="">
      <div id="menue" style="height: 80px;background-color: lightskyblue;color: #fff; padding: 15px;">
        <%= render 'layouts/menue' %>
      </div>

      <div id="bodyContent" style="padding: 0 25px;">
        <%= yield %>
      </div>

      <div id="footer" style="margin-top: 50px; height: 20px;background-color: lightskyblue;color: #fff; padding: 5px; text-align: center;">
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>